# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f791d3f1f269b4a56318674db4aab6009e522a872bccf8a855c52ad17b8d95c113a794e25229eded387e2d649936657f16c6e60a05107c90847bec4b750cdd

test:
  secret_key_base: 9b9b28f0449fb0a45a6b97e3521b45370cc32bf412beedb5197726f1074c77e573389c1f1442016fabc835e6be8b28e6fbb2b308f61177af7e19274fde7d0c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
